<?php
namespace Tests\Feature\Billing;
use App\Billing\EntitlementService;
use App\Billing\Enums\SubscriptionState;
use App\Billing\Exceptions\InvalidProviderSignatureException;
use App\Billing\Exceptions\QuotaExceededException;
use App\Billing\Providers\BillingProvider;
use App\Billing\SubscriptionService;
use App\Billing\UsageQuotaService;
use App\Models\BillingPlan;
use App\Models\BillingProviderCredential;
use App\Models\BillingProviderEvent;
use App\Models\BillingSubscriptionChange;
use App\Models\Permission;
use App\Models\Role;
use App\Models\Tenant;
use App\Models\TenantMembership;
use App\Models\TenantSubscription;
use App\Models\TenantUsageCounter;
use App\Models\User;
use App\Tenancy\TenantContext;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;
class BillingPlatformTest extends TestCase
{
    use RefreshDatabase;
    private FakePayPalProvider $provider;
    protected function setUp(): void { parent::setUp();$this->provider=new FakePayPalProvider;$this->app->instance(BillingProvider::class,$this->provider); }
    public function test_canonical_plan_catalog_is_persisted_and_public_contract_hides_provider_mapping(): void { $this->assertSame(['free-trial','starter','pro','business','enterprise'],BillingPlan::query()->orderBy('display_order')->pluck('code')->all());$response=$this->getJson('/api/v1/billing/plans')->assertOk();$response->assertJsonCount(5,'data');$this->assertStringNotContainsString('provider_plan_id',$response->getContent()); }
    public function test_trial_starts_without_payment_expires_and_cannot_be_reused(): void { [$tenant,$membership]=$this->tenantMember('alpha');$this->actingAs($membership->user)->postJson('/api/v1/tenants/alpha/billing/trial')->assertCreated()->assertJsonPath('data.state','TRIALING');$this->actingAs($membership->user)->postJson('/api/v1/tenants/alpha/billing/trial')->assertConflict()->assertJsonPath('code','BILLING_CONFLICT');$context=app(TenantContext::class);$context->activate($tenant,$membership);$s=TenantSubscription::query()->firstOrFail();$s->update(['trial_expires_at'=>now()->subMinute()]);app(SubscriptionService::class)->expireTrialsAndGrace();$this->assertSame(SubscriptionState::EXPIRED,TenantSubscription::query()->firstOrFail()->state);$context->forget(); }
    public function test_browser_checkout_never_activates_subscription_but_verified_provider_event_does(): void { [$tenant,$membership]=$this->tenantMember('alpha');$this->configurePlan('pro',4900,'P-PRO');$this->actingAs($membership->user)->postJson('/api/v1/tenants/alpha/billing/trial')->assertCreated();$checkout=$this->actingAs($membership->user)->postJson('/api/v1/tenants/alpha/billing/checkout',['plan_code'=>'pro'])->assertCreated()->assertJsonPath('data.status','PENDING_PROVIDER_CONFIRMATION');$this->assertStringContainsString('approve.test',$checkout->json('data.approval_url'));$context=app(TenantContext::class);$context->activate($tenant,$membership);$s=TenantSubscription::query()->firstOrFail();$this->assertSame(SubscriptionState::TRIALING,$s->state);$providerId=$s->encrypted_provider_subscription_id;$context->forget();$this->provider->event=['id'=>'evt-1','type'=>'BILLING.SUBSCRIPTION.ACTIVATED','provider_subscription_id'=>$providerId,'provider_plan_id'=>'P-PRO','occurred_at'=>now()->toAtomString(),'transaction_id'=>'','amount_minor'=>null,'currency'=>null,'payload_hash'=>hash('sha256','evt-1')];$this->postJson('/api/v1/billing/webhooks/paypal',['id'=>'ignored'])->assertOk()->assertJsonPath('status','processed');$context->activate($tenant,$membership);$s=TenantSubscription::query()->with('plan')->firstOrFail();$this->assertSame(SubscriptionState::ACTIVE,$s->state);$this->assertSame('pro',$s->plan->code);$context->forget(); }
    public function test_webhook_replay_is_idempotent_and_invalid_signature_does_not_mutate_state(): void { [$tenant,$membership]=$this->activePaid('alpha','pro','P-PRO');$context=app(TenantContext::class);$context->activate($tenant,$membership);$id=TenantSubscription::query()->value('encrypted_provider_subscription_id');$context->forget();$this->provider->event=['id'=>'evt-fail','type'=>'BILLING.SUBSCRIPTION.PAYMENT.FAILED','provider_subscription_id'=>$id,'provider_plan_id'=>'P-PRO','occurred_at'=>now()->toAtomString(),'transaction_id'=>'','amount_minor'=>null,'currency'=>null,'payload_hash'=>hash('sha256','evt-fail')];$this->postJson('/api/v1/billing/webhooks/paypal')->assertOk()->assertJsonPath('status','processed');$this->postJson('/api/v1/billing/webhooks/paypal')->assertOk()->assertJsonPath('status','duplicate');$this->assertSame(1,BillingProviderEvent::query()->count());$this->provider->reject=true;$this->postJson('/api/v1/billing/webhooks/paypal')->assertUnauthorized()->assertJsonPath('code','INVALID_PROVIDER_SIGNATURE');$this->assertSame(1,BillingProviderEvent::query()->count()); }
    public function test_payment_failure_grace_and_cancellation_are_explicit_provider_backed_states(): void { [$tenant,$membership]=$this->activePaid('alpha','pro','P-PRO');$context=app(TenantContext::class);$context->activate($tenant,$membership);$s=TenantSubscription::query()->firstOrFail();$id=$s->encrypted_provider_subscription_id;$context->forget();$this->provider->event=['id'=>'evt-past','type'=>'BILLING.SUBSCRIPTION.PAYMENT.FAILED','provider_subscription_id'=>$id,'provider_plan_id'=>'P-PRO','occurred_at'=>now()->toAtomString(),'transaction_id'=>'','amount_minor'=>null,'currency'=>null,'payload_hash'=>hash('sha256','evt-past')];$this->postJson('/api/v1/billing/webhooks/paypal')->assertOk();$context->activate($tenant,$membership);$this->assertSame(SubscriptionState::PAST_DUE,TenantSubscription::query()->firstOrFail()->state);app(SubscriptionService::class)->expireTrialsAndGrace();$this->assertSame(SubscriptionState::GRACE,TenantSubscription::query()->firstOrFail()->state);TenantSubscription::query()->firstOrFail()->update(['grace_ends_at'=>now()->subMinute()]);app(SubscriptionService::class)->expireTrialsAndGrace();$this->assertSame(SubscriptionState::SUSPENDED,TenantSubscription::query()->firstOrFail()->state);TenantSubscription::query()->firstOrFail()->update(['state'=>SubscriptionState::ACTIVE]);$context->forget();$this->actingAs($membership->user)->postJson('/api/v1/tenants/alpha/billing/cancel')->assertOk()->assertJsonPath('data.cancel_at_period_end',true);$this->assertTrue($this->provider->cancelled);$this->provider->event=['id'=>'evt-cancel','type'=>'BILLING.SUBSCRIPTION.CANCELLED','provider_subscription_id'=>$id,'provider_plan_id'=>'P-PRO','occurred_at'=>now()->toAtomString(),'transaction_id'=>'','amount_minor'=>null,'currency'=>null,'payload_hash'=>hash('sha256','evt-cancel')];$this->postJson('/api/v1/billing/webhooks/paypal')->assertOk();$context->activate($tenant,$membership);$this->assertSame(SubscriptionState::CANCELLED,TenantSubscription::query()->firstOrFail()->state);$context->forget(); }
    public function test_entitlements_and_atomic_quota_are_tenant_scoped_reset_by_period_and_reject_overage(): void { [$tenantA,$memberA]=$this->activePaid('alpha','pro','P-PRO-A');[$tenantB,$memberB]=$this->activePaid('beta','pro','P-PRO-B');$context=app(TenantContext::class);$context->activate($tenantA,$memberA);$this->assertTrue(app(EntitlementService::class)->may('seo.audit.enabled'));$this->assertFalse(app(EntitlementService::class)->may('nonexistent.feature'));app(UsageQuotaService::class)->consume('ai.requests.month',3000);$this->assertSame(0,app(UsageQuotaService::class)->remaining('ai.requests.month'));try{app(UsageQuotaService::class)->consume('ai.requests.month',1);$this->fail('Expected quota rejection.');}catch(QuotaExceededException){}$this->assertSame(3000,TenantUsageCounter::query()->value('amount_used'));$this->travel(1)->month();app(UsageQuotaService::class)->consume('ai.requests.month',1);$this->assertSame(1,TenantUsageCounter::query()->where('period_key',now()->format('Y-m'))->value('amount_used'));$this->travelBack();$context->forget();$context->activate($tenantB,$memberB);$this->assertNull(TenantUsageCounter::query()->first());app(UsageQuotaService::class)->consume('ai.requests.month',1);$this->assertSame(1,TenantUsageCounter::query()->value('amount_used'));$context->forget(); }
    public function test_downgrade_blocks_without_deleting_usage_and_upgrade_waits_for_provider_confirmation(): void { [$tenant,$membership]=$this->activePaid('alpha','pro','P-PRO');$this->configurePlan('starter',1900,'P-START');$this->configurePlan('business',9900,'P-BIZ');$context=app(TenantContext::class);$context->activate($tenant,$membership);TenantUsageCounter::query()->create(['metric'=>'ai.requests.month','period_key'=>now()->format('Y-m'),'amount_used'=>900,'limit_snapshot'=>3000,'period_started_at'=>now()->startOfMonth(),'period_ends_at'=>now()->endOfMonth()]);$context->forget();$this->actingAs($membership->user)->postJson('/api/v1/tenants/alpha/billing/change-plan',['plan_code'=>'starter'])->assertAccepted()->assertJsonPath('data.status','blocked');$context->activate($tenant,$membership);$this->assertSame(900,TenantUsageCounter::query()->value('amount_used'));$context->forget();$this->actingAs($membership->user)->postJson('/api/v1/tenants/alpha/billing/change-plan',['plan_code'=>'business'])->assertAccepted()->assertJsonPath('data.status','provider_pending');$this->assertSame('P-BIZ',$this->provider->changedTo);$context->activate($tenant,$membership);$s=TenantSubscription::query()->firstOrFail();$id=$s->encrypted_provider_subscription_id;$this->assertSame('pro',$s->plan->code);$context->forget();$this->provider->event=['id'=>'evt-updated','type'=>'BILLING.SUBSCRIPTION.UPDATED','provider_subscription_id'=>$id,'provider_plan_id'=>'P-BIZ','occurred_at'=>now()->toAtomString(),'transaction_id'=>'','amount_minor'=>null,'currency'=>null,'payload_hash'=>hash('sha256','evt-updated')];$this->postJson('/api/v1/billing/webhooks/paypal')->assertOk();$context->activate($tenant,$membership);$this->assertSame('business',TenantSubscription::query()->with('plan')->firstOrFail()->plan->code);$this->assertSame('completed',BillingSubscriptionChange::query()->where('kind','upgrade')->value('status'));$context->forget(); }
    public function test_cross_tenant_billing_is_not_disclosed_and_provider_identifiers_are_absent_from_api(): void { [$tenantA,$memberA]=$this->activePaid('alpha','pro','P-PRO');[,$memberB]=$this->tenantMember('beta');$this->actingAs($memberB->user)->getJson('/api/v1/tenants/alpha/billing/subscription')->assertNotFound();$response=$this->actingAs($memberA->user)->getJson('/api/v1/tenants/alpha/billing/subscription')->assertOk();$this->assertStringNotContainsString('provider_subscription',$response->getContent());$this->assertStringNotContainsString('encrypted_',$response->getContent()); }
    public function test_plan_admin_crud_clone_disable_reorder_and_active_retirement_safety_are_audited(): void { $admin=User::factory()->create();$admin->forceFill(['platform_admin'=>true])->save();$this->actingAs($admin)->postJson('/api/v1/billing/admin/plans',['code'=>'custom','name'=>'Custom','currency'=>'USD','billing_interval'=>'month','limits'=>[],'entitlements'=>[]])->assertCreated();$plan=BillingPlan::where('code','custom')->firstOrFail();$this->actingAs($admin)->putJson("/api/v1/billing/admin/plans/{$plan->id}",['name'=>'Custom Edited'])->assertOk();$this->actingAs($admin)->postJson("/api/v1/billing/admin/plans/{$plan->id}/clone",['code'=>'custom-copy','name'=>'Custom Copy'])->assertCreated();$this->actingAs($admin)->postJson("/api/v1/billing/admin/plans/{$plan->id}/enabled",['enabled'=>false])->assertOk();$this->actingAs($admin)->postJson('/api/v1/billing/admin/plans/reorder',['plans'=>[['code'=>'custom','display_order'=>9],['code'=>'custom-copy','display_order'=>10]]])->assertOk();$this->assertGreaterThanOrEqual(5,DB::table('billing_plan_audits')->where('actor_user_id',$admin->id)->count());[$tenant,$membership]=$this->activePaid('alpha','pro','P-PRO');$pro=BillingPlan::where('code','pro')->firstOrFail();$this->actingAs($admin)->postJson("/api/v1/billing/admin/plans/{$pro->id}/retire")->assertConflict()->assertJsonPath('code','BILLING_CONFLICT');$this->assertNull($pro->fresh()->retired_at); }
    public function test_provider_credentials_are_encrypted_and_never_exposed(): void { BillingProviderCredential::query()->create(['provider'=>'paypal','encrypted_credentials'=>['client_id'=>'client-x','client_secret'=>'super-secret','webhook_id'=>'hook-x']]);$raw=DB::table('billing_provider_credentials')->value('encrypted_credentials');$this->assertStringNotContainsString('super-secret',$raw);$this->assertArrayNotHasKey('encrypted_credentials',BillingProviderCredential::firstOrFail()->toArray());$this->assertStringNotContainsString('super-secret',$this->getJson('/api/v1/billing/plans')->getContent()); }
    private function configurePlan(string $code,int $price,string $providerPlanId): BillingPlan { $p=BillingPlan::where('code',$code)->firstOrFail();$p->update(['price_minor'=>$price,'provider'=>'paypal','provider_plan_id'=>$providerPlanId]);return$p; }
    private function activePaid(string $slug,string $planCode,string $providerPlanId): array { [$tenant,$member]=$this->tenantMember($slug);$plan=$this->configurePlan($planCode,4900,$providerPlanId);$context=app(TenantContext::class);$context->activate($tenant,$member);TenantSubscription::query()->create(['billing_plan_id'=>$plan->id,'state'=>SubscriptionState::ACTIVE,'provider'=>'paypal','provider_subscription_hash'=>hash('sha256','sub-'.$slug),'encrypted_provider_subscription_id'=>'sub-'.$slug,'started_at'=>now(),'current_period_end'=>now()->addMonth()]);$context->forget();return[$tenant,$member]; }
    private function tenantMember(string $slug): array { $tenant=Tenant::query()->create(['name'=>ucfirst($slug),'slug'=>$slug]);$user=User::factory()->create();$context=app(TenantContext::class);$context->activate($tenant);$membership=TenantMembership::query()->create(['user_id'=>$user->id,'status'=>'active']);$role=Role::query()->create(['name'=>'billing-owner']);foreach(['billing.view','billing.manage']as$name){$permission=Permission::query()->create(['name'=>$name]);$role->permissions()->attach($permission,['tenant_id'=>$tenant->id]);}$membership->roles()->attach($role,['tenant_id'=>$tenant->id]);$membership->setRelation('user',$user);$context->forget();return[$tenant,$membership]; }
}
final class FakePayPalProvider implements BillingProvider
{
    public array $event=[]; public bool $reject=false; public bool $cancelled=false; public ?string $changedTo=null;
    public function name(): string{return'paypal';} public function configured(): bool{return true;} public function createSubscriptionIntent(TenantSubscription $subscription,BillingPlan $plan): array{return['provider_subscription_id'=>'checkout-'.$subscription->id,'approval_url'=>'https://approve.test/'.$subscription->id,'status'=>'APPROVAL_PENDING'];} public function changeSubscription(TenantSubscription $subscription,BillingPlan $plan): array{$this->changedTo=$plan->provider_plan_id;return['requested'=>true];} public function cancelSubscription(TenantSubscription $subscription): void{$this->cancelled=true;} public function verifyAndParseWebhook(Request $request): array{if($this->reject)throw new InvalidProviderSignatureException('bad');return$this->event;} public function reconcile(TenantSubscription $subscription): array{return['status'=>'ACTIVE','provider_plan_id'=>$subscription->plan->provider_plan_id,'occurred_at'=>now()->toAtomString()];}
}
