<?php

return [
    // Focused closure production markers are the operation_id values on these
    // runtime-discovered contracts. Keep them attached to the real action wiring.
    'sites.connect' => [
        'operation_id' => 'AIMW-SYNC-E27768E92A',
        'canonical' => [
            'kind' => 'service',
            'domain' => 'sync',
            'route_screen' => 'service:SiteWebService',
            'visible_control' => 'AddSiteAsync',
            'current_source' => 'src/AIWordPressManager.Web/Services/SiteWebService.cs',
        ],
        'route_keys' => ['sites', 'site-connect'],
        'ownership' => 'tenant',
        'permission' => 'sites.manage',
        'capability' => 'sites.connect',
        'endpoint' => '/api/tenants/{tenant}/sites',
        'method' => 'POST',
        'reconcile_api_key' => 'sites',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => false,
        'fields' => [
            ['key' => 'name', 'type' => 'text', 'label' => ['en' => 'Site name', 'ar' => 'اسم الموقع'], 'required' => true],
            ['key' => 'url', 'type' => 'text', 'label' => ['en' => 'WordPress URL', 'ar' => 'رابط WordPress'], 'required' => true],
        ],
    ],
    'sites.refresh' => [
        'operation_id' => 'AIMW-SYNC-A9E956A4DA',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'sync',
            'route_screen' => '/sites',
            'visible_control' => '@(_refreshing ? (L.IsArabic ? [ReloadClickedAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/Sites.razor',
        ],
        'route_keys' => ['sites'],
        'ownership' => 'tenant',
        'permission' => 'tenant.view',
        'capability' => 'sites.refresh',
        'endpoint' => '/api/tenants/{tenant}/sites',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'sites',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'users.refresh' => [
        'operation_id' => 'AIMW-SYNC-724345B409',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'sync',
            'route_screen' => '/admin/application-users',
            'visible_control' => '@(L.IsArabic ? [RefreshClickedAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/ApplicationUsers.razor',
        ],
        'route_keys' => ['application-users'],
        'ownership' => 'tenant',
        'permission' => 'tenant.view',
        'capability' => 'users.refresh',
        'endpoint' => '/tenants/{tenant}/admin/members',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'application-users',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'users.disable' => [
        'operation_id' => 'AIMW-SYNC-6FCFE15D24',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'sync',
            'route_screen' => '/admin/application-users',
            'visible_control' => '@(L.IsArabic ? [ConfirmDisableAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/ApplicationUsers.razor',
        ],
        'route_keys' => ['application-users'],
        'ownership' => 'tenant',
        'permission' => 'members.manage',
        'capability' => 'users.disable',
        'endpoint' => '/tenants/{tenant}/admin/members/{membership}',
        'method' => 'PATCH',
        'reconcile_api_key' => 'application-users',
        'fixed' => ['status' => 'inactive'],
        'risk' => 'medium',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [
            ['key' => 'membership', 'type' => 'number', 'label' => ['en' => 'Membership ID', 'ar' => 'معرّف العضوية'], 'required' => true, 'path' => true],
        ],
    ],
    'roles.refresh' => [
        'operation_id' => 'AIMW-SYNC-7877CAF7E8',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'sync',
            'route_screen' => '/admin/roles-permissions',
            'visible_control' => '@(L.IsArabic ? [RefreshAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/RolesPermissions.razor',
        ],
        'route_keys' => ['roles'],
        'ownership' => 'tenant',
        'permission' => 'tenant.view',
        'capability' => 'roles.refresh',
        'endpoint' => '/tenants/{tenant}/admin/roles',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'roles',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'automation.refresh' => [
        'operation_id' => 'AIMW-AUTO-647F50CC73',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'automation',
            'route_screen' => '/automation-center',
            'visible_control' => 'RefreshAsync [RefreshAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/AutomationCenter.razor',
        ],
        'route_keys' => ['automation'],
        'ownership' => 'tenant',
        'permission' => 'operations.manage',
        'capability' => 'automation.refresh',
        'endpoint' => '/tenants/{tenant}/admin/automations',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'automation',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'schedules.refresh' => [
        'operation_id' => 'AIMW-BILL-5B1B140851',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'billing',
            'route_screen' => '/module/schedules | /automation-schedules',
            'visible_control' => '@(L.IsArabic ? [RefreshAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/AutomationSchedulesWorkspace.razor',
        ],
        'route_keys' => ['schedules'],
        'ownership' => 'tenant',
        'permission' => 'operations.manage',
        'capability' => 'schedules.refresh',
        'endpoint' => '/tenants/{tenant}/admin/schedules',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'schedules',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'execution.refresh' => [
        'operation_id' => 'AIMW-BILL-75CF9DBDA4',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'billing',
            'route_screen' => '/execution-center | /module/execution',
            'visible_control' => 'RefreshWithNotice [RefreshWithNotice]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/ExecutionCenter.razor',
        ],
        'route_keys' => ['execution'],
        'ownership' => 'tenant',
        'permission' => 'operations.manage',
        'capability' => 'execution.refresh',
        'endpoint' => '/tenants/{tenant}/admin/operations',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'execution',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'backups.refresh' => [
        'operation_id' => 'AIMW-BILL-07A0F6427B',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'billing',
            'route_screen' => '/backups | /module/backups',
            'visible_control' => 'Reload [Reload]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/BackupRestore.razor',
        ],
        'route_keys' => ['backups'],
        'ownership' => 'tenant',
        'permission' => 'backup.manage',
        'capability' => 'backups.refresh',
        'endpoint' => '/tenants/{tenant}/admin/backups',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'backups',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'logs.refresh' => [
        'operation_id' => 'AIMW-BILL-B9162DF5EF',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'billing',
            'route_screen' => '/logs | /module/logs',
            'visible_control' => 'Reload [Reload]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/LogsAndErrors.razor',
        ],
        'route_keys' => ['logs'],
        'ownership' => 'tenant',
        'permission' => 'operations.manage',
        'capability' => 'logs.refresh',
        'endpoint' => '/tenants/{tenant}/admin/logs',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'logs',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'notifications.refresh' => [
        'operation_id' => 'AIMW-EMAI-12A6FEB2FF',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'email',
            'route_screen' => '/notifications',
            'visible_control' => 'Reload [Reload]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/NotificationInbox.razor',
        ],
        'route_keys' => ['notifications'],
        'ownership' => 'tenant',
        'permission' => 'tenant.view',
        'capability' => 'notifications.refresh',
        'endpoint' => '/api/v1/tenants/{tenant}/notifications',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'notifications',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'email-history.refresh' => [
        'operation_id' => 'AIMW-BILL-090028F39C',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'billing',
            'route_screen' => '/email/history',
            'visible_control' => 'LoadAsync [LoadAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/EmailDeliveryHistory.razor',
        ],
        'route_keys' => ['email-history'],
        'ownership' => 'tenant',
        'permission' => 'tenant.manage',
        'capability' => 'email-history.refresh',
        'endpoint' => '/api/v1/tenants/{tenant}/email/deliveries',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'email-history',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'comments.refresh' => [
        'operation_id' => 'AIMW-SYNC-8D6F1C5EAA',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'sync',
            'route_screen' => '/sites/{SiteId:guid}/comments',
            'visible_control' => '@L[ [RefreshClickedAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/CommentsManager.razor',
        ],
        'route_keys' => ['comments'],
        'ownership' => 'site',
        'permission' => 'content.view',
        'capability' => 'comments.refresh',
        'connector_scope' => 'comments.read',
        'endpoint' => '/api/v1/tenants/{tenant}/sites/{site}/comments',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'comments',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'media.refresh' => [
        'operation_id' => 'AIMW-SYNC-461B1075DE',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'sync',
            'route_screen' => '/sites/{SiteId:guid}/media',
            'visible_control' => '@L[ [RefreshClickedAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/MediaManager.razor',
        ],
        'route_keys' => ['media'],
        'ownership' => 'site',
        'permission' => 'content.view',
        'capability' => 'media.refresh',
        'connector_scope' => 'media.read',
        'endpoint' => '/api/v1/tenants/{tenant}/sites/{site}/media',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'media',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'taxonomy.refresh' => [
        'operation_id' => 'AIMW-SYNC-0FF542A678',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'sync',
            'route_screen' => '/sites/{SiteId:guid}/taxonomy',
            'visible_control' => '@L[ [RefreshClickedAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/TaxonomyManager.razor',
        ],
        'route_keys' => ['taxonomy'],
        'ownership' => 'site',
        'permission' => 'content.view',
        'capability' => 'taxonomy.refresh',
        'connector_scope' => 'taxonomy.read',
        'endpoint' => '/api/v1/tenants/{tenant}/sites/{site}/taxonomy',
        'method' => 'GET',
        'ui_role' => 'refresh',
        'reconcile_api_key' => 'taxonomy',
        'risk' => 'low',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'taxonomy.manage' => [
        'operation_id' => 'AIMW-BILL-B15FB13792',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'billing',
            'route_screen' => '/sites/{SiteId:guid}/taxonomy',
            'visible_control' => 'SaveAsync [SaveAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/TaxonomyManager.razor',
        ],
        'route_keys' => ['taxonomy'],
        'ownership' => 'site',
        'permission' => 'content.edit',
        'capability' => 'taxonomy.manage',
        'endpoint' => '/api/v1/tenants/{tenant}/sites/{site}/taxonomy',
        'method' => 'POST',
        'reconcile_api_key' => 'taxonomy',
        'risk' => 'medium',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [
            ['key' => 'taxonomy', 'type' => 'select', 'label' => ['en' => 'Taxonomy', 'ar' => 'التصنيف'], 'required' => true, 'options' => [
                ['value' => 'category', 'label' => ['en' => 'Category', 'ar' => 'تصنيف']],
                ['value' => 'post_tag', 'label' => ['en' => 'Tag', 'ar' => 'وسم']],
            ]],
            ['key' => 'name', 'type' => 'text', 'label' => ['en' => 'Name', 'ar' => 'الاسم'], 'required' => true],
            ['key' => 'slug', 'type' => 'text', 'label' => ['en' => 'Slug', 'ar' => 'الرابط المختصر']],
            ['key' => 'description', 'type' => 'textarea', 'label' => ['en' => 'Description', 'ar' => 'الوصف']],
            ['key' => 'parent', 'type' => 'number', 'label' => ['en' => 'Parent ID', 'ar' => 'معرّف الأصل']],
        ],
    ],
    'sync.run' => [
        'operation_id' => 'AIMW-BILL-37EE8ED7EE',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'billing',
            'route_screen' => '/module/sync',
            'visible_control' => '@(L.IsArabic ? [RunSynchronizationAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/GlobalSynchronizationWorkspace.razor',
        ],
        'route_keys' => ['sync'],
        'ownership' => 'site',
        'permission' => 'content.edit',
        'capability' => 'sync.run',
        'endpoint' => '/api/v1/tenants/{tenant}/sites/{site}/sync',
        'method' => 'POST',
        'fixed' => ['full' => false],
        'reconcile_api_key' => 'sync',
        'risk' => 'medium',
        'approval_required' => false,
        'terminal_candidate' => true,
        'fields' => [],
    ],
    'seo.audit.run' => [
        'operation_id' => 'AIMW-BILL-3C55B3C299',
        'dependency_operation_id' => 'AIMW-SEO-FB0F0E9067',
        'canonical' => [
            'kind' => 'visible_control',
            'domain' => 'billing',
            'route_screen' => '/sites/{Id:guid}/seo',
            'visible_control' => 'RunFullAuditAsync [RunFullAuditAsync]',
            'current_source' => 'src/AIWordPressManager.Web/Components/Pages/SeoManager.razor',
        ],
        'route_keys' => ['seo-audit'],
        'ownership' => 'site',
        'permission' => 'seo.manage',
        'capability' => 'seo.audit.run',
        'endpoint' => '/api/tenants/{tenant}/sites/{site}/seo/audits',
        'method' => 'POST',
        'reconcile_api_key' => 'seo-audit',
        'risk' => 'high',
        'approval_required' => true,
        'terminal_candidate' => false,
        'blocked_reason' => 'Canonical SEO audit execution is approval-required, but the current Laravel endpoint dispatches immediately.',
        'fields' => [],
    ],
];
