<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>155.6.0</Version>
    <AssemblyVersion>155.6.0.0</AssemblyVersion>
    <FileVersion>155.6.0.0</FileVersion>
    <InformationalVersion>155.6.0</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AIWordPressManager.Application\AIWordPressManager.Application.csproj" />
    <ProjectReference Include="..\AIWordPressManager.Domain\AIWordPressManager.Domain.csproj" />
    <ProjectReference Include="..\AIWordPressManager.Infrastructure\AIWordPressManager.Infrastructure.csproj" />
    <ProjectReference Include="..\AIWordPressManager.Persistence\AIWordPressManager.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>